let obj = [
   {
      name: "Abarrotes",
      data: [
         { plat: "Aceite 123 500 ml   ", cost: 23 },
         { plat: "Aceite 123 1 litro.      ", cost: 43 },
         { plat: "Aceite Olivo Pz 45 Ml.  ", cost: 8 },
         { plat: "Agua bonafont 1.5 Lt.    ", cost: 12 },
         { plat: "Alpura 1L      ", cost: 26 },
         { plat: "Ariel 250 Ml.       ", cost: 13.5 },
         { plat: "Atún dolores aceite 133 Gr. ", cost: 22 },
         { plat: "Atún Hernandez aceite 132 Gr. ", cost: 22 },
         { plat: "Bbq orig Hunts 360 Gr.  ", cost: 36 },
         { plat: "Big papel 600 hoj ", cost: 38 },
         { plat: "Blanca nieves 250 g   ", cost: 10 },
         { plat: "Boing 250 ml guayaba/mango/manzana/uva.     ", cost: 9 },
         { plat: "Carisma Liq 1L. ", cost: 41 },
         { plat: "Castup Clemente Jacques 220 Gr", cost: 41 },
         { plat: "Ensalada de verduras 220 Gr", cost: 13 },
         { plat: "Elote costeña 410 Gr  ", cost: 20 },
         { plat: "Ensueño fresca azul 850 ml", cost: 26 },
         { plat: "Fabuloso 500 ml. ", cost: 19 },
         { plat: "Gerber fruta mixta 100 Gr", cost: 13 },
         { plat: "Hot Cakes Tres estrellas 1 kg", cost: 42 },
         { plat: "Jabón Ace 500 g   ", cost: 23 },
         { plat: "Jabón rosa zote.   ", cost: 12 },
         { plat: "Jalapeños morena", cost: 15 },
         { plat: "Jumex durazno/ mango/ manzana 475 ml", cost: 14 },
         { plat: "Maíz palomero 250 Gr", cost: 7.5 },
         { plat: "Marlboro rojo.", cost: 5 },
         { plat: "Maruchan camarón sol", cost: 17 },
         { plat: "Mayonesa 228 Gr", cost: 36, },
      ]
   },{
      name: "Barquillo",
      data: [
         { plat: "Barquillo Chocolate-Cuetara-290gr", cost: 44 },
         { plat: "Barquillo Chocolate-Cuetara-570gr", cost: 79 },
         { plat: "Barquillo Con Malvavisco Momoman-Lu...", cost: 53 },
         { plat: "Barquillo Mary", cost: 41 },
         { plat: "Barquillo Wafer Kalu-Kalu-180pz", cost: 115 },
         { plat: "Wafer Calu Chocolate 85 Pz 422g", cost: 60 },
      ]
   },{
      name: "Bombones",
      data: [
         {plat: "Bianchi Corazon Supergigante",cost: 65},
         {plat: "Blanchi Gr Colores 400gr",cost: 36},
         {plat: "Bianchi Mediano Colores 400gr",cost: 36},
         {plat: "Bianchi Menta Cj 50pz",cost: 76},
         {plat: "Bombon Bianchi Ch Azul-Rosa 400gr",cost: 36},
         {plat: "Bombon Bianchi Ch Colores-Rosa 400gr",cost: 36},
         {plat: "Bombon Bianchi ChocoCorazon-Rosa-5",cost: 76},
         {plat: "Bombon Bianchi Chocolate-Rosa-32pz",cost: 85.5},
         {plat: "Bombon Bianchi Chocolate-Rosa-50pz",cost: 76},
         {plat: "Bombon Bianchi Corazon-Rosa-400gr",cost: 538},
         {plat: "Bombon Bianchi Enrollados-La Rosa-40",cost: 36},
         {plat: "Bombon Bianchi Figuras Con, Osit, Poll-..",cost: 38},
         {plat: "Bombon Bianchi Gra-Rosa 400gr",cost: 936},
         {plat: "Bombon Bianchi Med-Rosa 400gr",cost: 36},
         {plat: "Bombon Bianchi Mini Rosa- 400gr",cost: 37},
         {plat: "Bombon Bianchi Minimini-Rosa 30pz",cost: 103},
         {plat: "Bombon Coffis-Products 50 Pz",cost: 71.5},
         {plat: "Bombon Malvalleno Chocolate Mix-Can",cost: 65.5},
         {plat: "Bombon Tapon-Bremen 200gr",cost: 51}
      ]
   },{
      name: "Botanas/Chicharrones",
      data: [
         {plat: "Anillo a Granel", cost: 100},
         {plat: "Anillo Rueda-La Muñeca lkg", cost: 70},
         {plat: "Bofitos-Kipi 25pz", cost: 29.5},
         {plat: "Bolita Solchesito-Sol-100gr", cost: 9},
         {plat: "Cacahuate Botana Surtida-Sol- 1kg", cost: 77.5},
         {plat: "Cacahuate Enchilado A La Mita", cost: 120},
         {plat: "Cacahuate Estilo Japones-Sol-lkg", cost: 65.5},
         {plat: "Cacahuate Estilo tapones-Xalii-25pz", cost: 46},
         {plat: "Cacahuate Estilo Japones-Xalit-50pz", cost: 49},
         {plat: "Cacahuate Garapiñado C/Ajonjoli-lkd", cost: 69},
         {plat: "Cacahuate Queso Aguilar lkg", cost: 60},
         {plat: "Cacahuate Tipo Español Sol lkg ", cost: 71},
         {plat: "Cacahuate Tipo Espqñol C/Ajo-Sol-11<g ", cost: 75.5},
         {plat: "Caseras Personal Sal Negra ", cost: 54},
         {plat: "Caseras Salsa Negra 10 Pz 34gr", cost: 74},
         {plat: "Caseras Kuibo 10pz", cost: 75},
         {plat: "Caseras Zig-Zag 10 Pz ", cost: 75},
         {plat: "Cheto La Muñeca ", cost: 58},
         {plat: "Chicharron Para Preparar-Friturkas-20pz ", cost: 37},
      ]
   },{
      name: "Chicles",
      data: [
         {plat: "Bombi Crayon-Carr-Goma De Mascar-24 ", cost: 48},
         {plat: "Chicle Bubli Bubli-Gomez-100pz ", cost: 66},
         {plat: "Chicle Canels Frutal-Canels-C60-Paq ", cost: 49},
         {plat: "Chicle En Polvo ", cost: 42},
         {plat: "Chicle Icce-Cereza 45pz ", cost: 44},
         {plat: "Chicle Orbit Fresa 4s-Effem-40paq ", cost: 98},
         {plat: "Chicle Orbit Menta 4s-Effem-40paq ", cost: 98},
         {plat: "Chicle Trident Yerbabuena 18s-Mondel", cost: 80},
         {plat: "Chicles Bubbaloo Surtido-Mundelez-47pz ", cost: 43},
         {plat: "Chicles Canels Orig- 4Tab Caja ", cost: 49},
         {plat: "Chicles Clorets 2s-Mondelez-60pz ", cost: 51},
         {plat: "Chicles Clorets Plus 4s-Mondelez-40paq ", cost: 74},
         {plat: "Chicles Orbit Hierbabuena 4s-Effem-40", cost: 98},
         {plat: "Chicles Orbit Polar Mint 4s-Effem-40paq ", cost: 98},
         {plat: "Orbit Hierbabuena ", cost: 3},
         {plat: "Trident Chicles 4 Pastillas ", cost: 84},
         {plat: "Usther Pastilla Menta ", cost: 44},
      ]
   },{
      name: "Chocolate",
      data: [
         {plat: "Arma Tu Mini Paleta Payaso ", cost: 22},
         {plat: "Baileys Original-Turin-Bolsa 120gr ", cost: 91 },
         {plat: "Balleys Avellana-Bailleys ", cost: 136},
         {plat: "Bocadin Pastrlito", cost: 52},
         {plat: "Bolitas De Chocolate-Floops-lkg ", cost: 180 },
         {plat: "CHOCOLATE VAQUERO-La Esperanza", cost: 86 },
         {plat: "Carlos V Amargo-Nestle-16 Pz", cost: 101},
         {plat: "Carlos V Galleta-Nestle-15pz ", cost: 65},
         {plat: "Carlos V Orig Prom", cost: 108 },
         {plat: "Carlos V Semi Amargo ", cost: 8},
         {plat: "Carlos V Stick Blanco 20 Pz ", cost: 52},
         {plat: "Carlos V Stick-Nestle-20pz ", cost: 52},
         {plat: "Carlos V Zuizo-16", cost: 117},
         {plat: "Cerize Licor Cereza-Bremen-300gr ", cost: 115},
         {plat: "Choc Bubu-Lubu Gr-Ricolino-12pz", cost: 102},
         {plat: "Choc Bubulubu Min-Ricolino-25pz ", cost: 92  },
         {plat: " Choc Snickers/Milkyway Surtido-Mars", cost: 59 },
         {plat: "ChocBocadin-Ricolino- c50 pz", cost: 69.5},
         {plat: "Choco Freskys Bolsa 240", cost: 65},
      ]
   },{
      name: "Dulces Duro, Chicloso",
      data: [
         {plat: "Aguitas Gr-Gomez- 100pz", cost: 37},
         {plat: "Aguitas Suave", cost: 39},
         {plat: "Astridix-Palola-30pz", cost: 48.5},
         {plat: "Bastoncitos-200gr", cost: 40},
         {plat: "Bibi Polviz", cost: 7},
         {plat: "Bibifrutix-Pillo-12pz", cost: 61},
         {plat: "Bibipolviz-Pillo-12pz", cost: 61},
         {plat: "Bolsa Piñatera Halloween 1.3", cost: 200},
         {plat: "Bolsa Piñatera-Candies Supplier-1.400g", cost: 210},
         {plat: "Bota Navidea Mediana ", cost: 50},
         {plat: "3rementas-Bremen-100pz", cost: 43},
         {plat: "Cachitos- Montes- C100 .", cost: 68},
         {plat: "Caramelitos Sabor Frutas-Rosa-500gr", cost: 44},
         {plat: "Caramelo De La Rosa c100 Dulces", cost: 37},
         {plat: "Caramelo Ron Mantequilla-La Posse-", cost: 87},
         {plat: "Caramelos Pulparindo Surtido-Rosa-10", cost: 42},
         {plat: "Cerecets Brem-Brem-lkg", cost: 96},
         {plat: "Chidosos-Coronado-250gr", cost: 42},
         {plat: "Chocoretas Mini-Ricolino-25pz", cost: 69},

      ]
   },{
      name: "Dulces Granel",
      data: [
         {plat: "Ajo Cachuate-lkg", cost: 160},
         {plat: "Almendras ", cost: 140},
         {plat: "Aros Durazno ", cost: 150},
         {plat: "Aros Manzana ", cost: 130},
         {plat: "Astridix ", cost: 2},
         {plat: "BIBI DULCE ", cost: 7},
         {plat: "BOCADIN PZ ", cost: 2},
         {plat: "BUBBALOO", cost: 2},
         {plat: "BUBULU MINI ", cost: 6},
         {plat: "Barquillos Cuetara Suelto ", cost: 1.5},
         {plat: "Bocadin Pastelito ", cost: 7},
         {plat: "Bofos Valentina ", cost: 100},
         {plat: "Bombon Cafe ", cost: 2},
         {plat: "Bombon Mini Pz ", cost: 4},
         {plat: "Bombon Relleno Chocolate ", cost: 3},
         {plat: "BubuLubu Ricolino 35g Grande ", cost: 9},
         {plat: "Burbu Soda Like ", cost: 3.5},
         {plat: "CHOCOLATE ROSA PZ ", cost: 9},
         {plat: "CHURRUS ", cost: 12},
         {plat: "CLASICA", cost: 2},
         {plat: "COCADAS 62PZ", cost: 2},
         {plat: "Crayon SABORES PZ", cost: 9},
         {plat: "Cabada La Piedad 30g PZ", cost: 5},
         {plat: "Cacahuate Chipotle-1 Kg", cost: 100},
         {plat: "Cacahuate Habanero-lkg", cost: 100},
         {plat: "Cacahuate Queso.lkg", cost: 100},
         {plat: "Cacahuate Salado Aguilar", cost: 110},
         {plat: "Cacahuate Surtido Con Pistach", cost: 160},
         {plat: "Caritas Pz", cost: 2},
         {plat: "Cerezas-Brem-lkg", cost: 160},
         {plat: "Chicles Canels 4s", cost: 2},
         {plat: "ChocolNugs por pieza", cost: 5},
         {plat: "Chocolate Malvabon", cost: 5},
         {plat: "Chocolate Malvabon Fresa", cost: 5},
         {plat: "Chocoreta-Menta-lkg", cost: 120},
         {plat: "Chocoretas Pz", cost: 4},
      ]
   },{
      name: "Galletas",
      data: [
         {plat: "Carajillo Licores ", cost: 90},
         {plat: "Galleta Deju-Mac Ma-2SOgr ", cost: 76},
         {plat: "Galleta Escoces-Mac Ma-330gr ", cost: 71},
         {plat: "Galleta Mini Mamut-Gamesa-28pqt ", cost: 48},
         {plat: "Galleta Presidente-Mac Ma-350gr ", cost: 75},
         {plat: "Galleta Selecciones-Mac Ma-330gr ", cost: 71},
         {plat: "Galleta Surtido Rico-Gamesa-436gr ", cost: 50},
         {plat: "Mac Ma-Gofrenata-320 Gr ", cost: 75},
         {plat: "Mamut Gr 240 Gr ", cost: 48},
         {plat: "Peke Pakes-Gamesa-14pz ", cost: 50},
         {plat: "Real Galleta-MacfMa-350gr ", cost: 73},
         {plat: "Surtido De Galletas-Mac Ma Bote ", cost: 132},
         {plat: "Surtido Rico Navidad ", cost: 60},
         {plat: "Surtido Rico-Gamesa ", cost: 64},
         {plat: "Wafer Kalu Capuchino 150 Pz ", cost: 115},
      ]
   },{
      name: "Tamarindos",
      data: [
         {plat: "Acidito Aciduladito Chile-Rosa-100pz", cost: 54},
         {plat: "Bombaso Tamar-Lucas Vaso-lOpz", cost: 68},
         {plat: "Bomvaso Limon 10 Pz", cost: 77},
         {plat: "Chicote Chile Gra", cost: 20},
         {plat: "Chicote Dulce Gr", cost: 20},
         {plat: "Crayon Manzana-Effem-lOpz", cost: 68},
         {plat: "Crayon Surtido-Hershey-lOpz", cost: 78},
         {plat: "Cucha Gol Mini-Lusi-20pz", cost: 17},
         {plat: "Dartañan Chamoy-24 Pz", cost: 63},
         {plat: "Frutimich Salsa Fuego", cost: 59},
         {plat: "Frutimich Mango-Miche", cost: 66},
         {plat: "Gusano Chamoy-Effem-19pz", cost: 71},
         {plat: "Lucas Muecas Chamoy-Effem-10pz", cost: 77},
         {plat: "Lucas Muecas Tamarindo-Effem-lOpz", cost: 71},
         {plat: "Lucas Panzon-Effem-10 Pz", cost: 78},
         {plat: "Mega Huevon-Pigui-30pz", cost: 47},
         {plat: "Mich Fruti Picante", cost: 59},
         {plat: "Miguelito Mora Azul", cost: 60},
         {plat: "Miguelito Sandia", cost: 60},

      ]
   },{
      name: "Salsas",
      data: [
         {plat: "Botanera Reducida En Sodio", cost: 14.5},
         {plat: "Burbu Soda Picante Sabor Naranja", cost: 33.5},
         {plat: "Burbusoda-Anahuac-60pz", cost: 24},
         {plat: "Chamoy Mega-Mega Alimentos- 1L", cost: 32},
         {plat: "Chamoy Mega-Mega Alimentos-370m1", cost: 17.5},
         {plat: "Chamoy Mega-Mega Alimentos-500m1", cost: 21},
         {plat: "Chamoy Original-Niega Alimentos-1.5 Lts", cost: 46},
         {plat: "Chilerito Chamoy-Chilera Tapatia-1.5 Lt", cost: 42.5},
         {plat: "Chilito Botanera-Mega Alimentos-125gr", cost: 27},
         {plat: "Dragonzitos-Ber-Ber-100pz", cost: 29},
         {plat: "Fruti Mich Mango Liq 1 Lts", cost: 59},
         {plat: "Frutimich Mora Liq 1 Lts", cost: 59},
         {plat: "Frutimich Sandia Lig 1 Lts", cost: 59},
         {plat: "Frutimuch Fresa Chamoy 1.1", cost: 66},
         {plat: "La Anita Tajin Orignal-150gr", cost: 30},
         {plat: "La Sabrozita -Salsa Picante-1.5", cost: 34},
         {plat: "La Sabrozita-lIt", cost: 26},
         {plat: "Limon 7-4Opz", cost: 24.5},
         {plat: "Limon 7-80pz", cost: 32},
      ]
   },{
      name: "Paletas",
      data: [
         {plat: "", cost: 0},
         {plat: "Paleta Cajeta Coronad Ch-Coronado-2", cost: 19.5},
         {plat: "Paleta Pachicleta-Cuanda- 20pzas", cost: 52},
         {plat: "Bomba Chile-Vero-40pz", cost: 62},
         {plat: "Bombas Surtidas-Vero 40 Pz", cost: 64},
         {plat: "Botella Cola-Alvher-40pz", cost: 52},
         {plat: "Burbu Soda Like-Mora", cost: 67},
         {plat: "Chupirul-Luxus-40pz", cost: 82},
         {plat: "Con Corazon-Paleta Cool Toons-40pz", cost: 54},
         {plat: "Corazon Neon-24 Fz", cost: 62},
         {plat: "Coronado Ch Paleta 20 Fz", cost: 18},
         {plat: "Cupido Chamoy-Vero-40pz", cost: 63},
         {plat: "Cupido Dulce-Vero-40pz . po", cost: 87},
         {plat: "Elote -Vero-40pz", cost: 78},
         {plat: "Fire Sandia", cost: 2},
         {plat: "Lacer Paleta", cost: 78},
         {plat: "Laser Paleta Promo 24", cost: 70},
         {plat: "pala Dedo Gra-Beny-40pz", cost: 63.5},
         {plat: "Pale-Locas-Luxus-25pz", cost: 59},
         {plat: "paleta Aquitas-Gomez-40pz", cost: 39},
      ]
   },{
      name: "Chocolates",
      data: [
         {plat: "Ferrero 4pz", cost: 45},
         {plat: "Ferrera Collection Corazon", cost: 122},
         {plat: "Ferrero Collection-11 Pz", cost: 110},
         {plat: "Ferrero Collection-7pz Ferrero", cost: 80},
         {plat: "Ferrero De Corazon 8pz", cost: 98},
         {plat: "Ferrero Rocher Baul -Roche-16pz", cost: 143},
         {plat: "Ferrero Rocher Diaman-Roche-24pz", cost: 240},
         {plat: "Ferrero-Ferrero Roche-8pz", cost: 88},
         {plat: "Giselle Relleno Caereza- 160 Gr Hexagonal", cost: 48},
         {plat: "Giselle-500gr", cost: 75},
         {plat: "Hershey Ss Fresa Con Craina 10 Barra", cost: 70},
         {plat: "Hershey S Hearts 123gr", cost: 80},
         {plat: "Hershey Unicornio- 10 Pz", cost: 70},
         {plat: "Hersheys Coffe Caramelo Tubo", cost: 135},
         {plat: "Hersheys Coffee 96 Gr Bolsa", cost: 85},
         {plat: "Huevito Colorida Sorpresa", cost: 24},
         {plat: "Huevito Dinosaurio", cost: 24},
         {plat: "Huevito Kinder Colorida Sorpresa-8pz ", cost: 170},
      ]
   },
]







